---
- hosts: localhost
  tasks:

# Setup apache, this may end up in apache.yml
  - name: Create the apache user.
    user:
        name: apache
        comment: Apache Server
        shell: /sbin/nologin
        home: /var/www

  - file:
        path: /usr/sbin/suexec
        group: apache
        mode: 4750

# Setup horizon
  - name: Create the horizon user.
    user:
        name: horizon
        comment: Openstack Horizon User
        shell: /sbin/nologin
        home: /var/lib/horizon

  - name: Fix permissions in /var/lib/horizon
    file:
        path: /var/lib/horizon
        state: directory
        owner: horizon
        group: horizon
        recurse: yes

  - name: Link horizon apache configuration
    file:
        src: /etc/horizon/apache-horizon.conf
        dest: /etc/httpd/conf.d/apache-horizon.conf
        state: link

  - name: Enable and start apache services needed by horizon
    service:
        name: "{{ item }}"
        enabled: yes
        state: started
    with_items:
    - apache-httpd.service
