# Test systems for CVE-2015-0235 GHOST
#
# http://www.openwall.com/lists/oss-security/2015/01/27/9
---
- hosts: all
  gather_facts: False
  tasks:
    - name: copy in the cve-2015-0235-ghost-x86-64 test program
      copy: src=cve-2015-0235-ghost-x86-64 dest=~ mode=755

    - name: run the test program
      command: ~/cve-2015-0235-ghost-x86-64
      register: test_output

    - debug: var=test_output.stdout_lines

    - name: remove test program again
      file: path=~/cve-2015-0235-ghost-x86-64 state=absent
