#!/bin/sh
#
# Copyright (C) 2014 Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

gem install bundler

git config --global http.sslVerify false
git config --global user.name 'GitLab CI Runner'
git config --global user.email 'ci_runner@localhost'
git config --global core.autocrlf input

git clone https://gitlab.com/gitlab-org/gitlab-ci-runner.git -b 5-0-stable
cd gitlab-ci-runner

bundle install --deployment
bundle exec ./bin/setup
nohup bundle exec ./bin/runner &

cd /etc/systemd/system
cp /usr/share/gitlab-install/systemd-units/gitlab-ci-runner.service .
systemctl enable gitlab-ci-runner.service
